---
  - name: Copy deploy script
    copy:
      src: ../files/getapp.sh
      dest: /var/lib/tomcat9/webapps/getapp.sh
      mode: u+rwx


  - name: Deploy project
    shell: /var/lib/tomcat9/webapps/getapp.sh
    args:
      chdir: /var/lib/tomcat9/webapps


  - name: Restart Web-services
    service:
      name: tomcat9
      state: restarted
