---
  - name: Pull image
    docker_image:
      name: igluckall/myapp:1.0
      source: pull


  - name: Run application
    docker_container:
      name: myapp
      image: igluckall/myapp:1.0
      state: started
      restart: yes
      ports: "80:8080"
