---
  - name: Download app sources
    git:
      repo: 'https://github.com/jenkinsci/jenkins.git'
      dest: /srv

  - name: Copy build script
    copy:
      src: ../files/build.sh
      dest: /srv/build.sh
      mode: u+rwx


  - name: Build project
    shell: /srv/build.sh
    args:
      chdir: /srv

  - name: Create directory for build
    file:
      path: /tmp/build
      state: directory
      mode: '0755'

  - name: Copy app to build directory
    copy:
      src: /srv/war/target/jenkins.war
      dest: /tmp/build/jenkins.war
      remote_src: yes
